---
targets:
- alias: live
  vars:
    env: live
  uri: dashboard.internet.nl
- alias: staging
  vars:
    env: staging
  uri: acc.dashboard.internet.nl
- alias: lab
  vars:
    env: lab
  config:
    ssh:
      user:
        _plugin: env_var
        var: SSH_USER
        default: root
  uri:
    _plugin: env_var
    var: LAB_URI
    default: localhost
config:
  ssh:
    native-ssh: true
    ssh-command: /usr/bin/ssh
    host-key-check: false
    run-as: root
